global:
  crds: false
  nodePort: false
  proxy:
    includeIPRanges: "10.28.0.0/14,10.7.240.0/20"

ingress:
  enabled: false

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: false

gateways:
  enabled: true

grafana:
  enabled: true

prometheus:
  enabled: true

servicegraph:
  enabled: true

tracing:
  enabled: true

certmanager:
  enabled: true
