apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.12.0
  values:
    metricsServer: http://prometheus.istio-system:9090
    image:
      repository: weaveworks/flagger
      tag: fix-vs-c92230c
      pullPolicy: IfNotPresent
    slack:
      user: flagger
      channel: general
      url: https://hooks.slack.com/services/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