---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-test
  namespace: default
  labels:
    app: podinfo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: podinfo
