---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: glob:1.2*
    flux.weave.works/tag.podinfod: glob:1.0*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
      - name: init
        image: quay.io/stefanprodan/podinfo:1.0.0
        command:
        - ./podinfo
        - --version
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:1.0.0
        command:
        - ./podinfo
        - --port=9898
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - wget --quiet --tries=1 --spider http://localhost:9898/healthz || exit
              1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - wget --quiet --tries=1 --spider http://localhost:9898/readyz || exit
              1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
