---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        prometheus.io/scrape: 'true'
        flux.weave.works/automated: "true"
        flux.weave.works/tag.podinfoinit: glob:1*
        flux.weave.works/tag.podinfod: glob:1*
    spec:
      initContainers:
        - name: podinfoinit
          image: quay.io/stefanprodan/podinfo:1.0.0
          command:
            - /bin/sh
            - -c
            - sleep 1
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:1.0.0
        command:
          - ./podinfo
          - --port=9898
          - --level=debug
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - wget --quiet --tries=1 --spider http://localhost:9898/healthz || exit 1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - wget --quiet --tries=1 --spider http://localhost:9898/readyz || exit 1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
