---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.blue: glob:1.0.0
    flux.weave.works/tag.green: semver:~1.0
spec:
  chartGitPath: podinfo-istio
  releaseName: frontend
  values:
    host: podinfo.istio.weavedx.com
    exposeHost: true

    blue:
      replicas: 2
      image: quay.io/stefanprodan/podinfo:1.0.0
      message: "Hello Container Camp"
      backend: http://backend:9898/api/echo

    green:
      replicas: 0
      image: quay.io/stefanprodan/podinfo:1.0.0
      routing:
        # target Safari
      - match:
        - headers:
            user-agent:
              regex: "^(?!.*Chrome).*Safari.*"
        # target API clients by version 1.0.1-1.0.9
      - match:
        - headers:
            x-api-version:
              regex: "^(v{0,1})1\\.0\\.([1-9]).*"
      message: "Greetings from the green frontend"
      backend: http://backend:9898/api/echo

