apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.blue: glob:1.0.0
    flux.weave.works/tag.green: glob:*
spec:
  chartGitPath: podinfo-istio
  releaseName: frontend
  values:
    host: podinfo.istio.weavedx.com
    exposeHost: true

    blue:
      replicas: 2
      repository: quay.io/stefanprodan/podinfo
      tag: "1.0.0"
      message: "Greetings from the blue frontend"
      backend: http://backend:9898/api/echo

    green:
      replicas: 2
      repository: quay.io/stefanprodan/podinfo
      tag: "1.0.0"
      routing:
        # target Safari
        - match:
          - headers:
              user-agent:
                regex: "^(?!.*Chrome).*Safari.*"
        # target API clients by version
        - match:
          - headers:
              x-api-version:
                regex: "^(v{0,1})0\\.6\\.([1-9]).*"
      message: "Greetings from the green frontend"
      backend: http://backend:9898/api/echo

