apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/ignore: "false"
spec:
  chartGitPath: istio
  releaseName: istio
  values:
    global:
      nodePort: false

    ingress:
      enabled: false

    sidecarInjectorWebhook:
      enabled: true
      enableNamespacesByDefault: false

    gateways:
      enabled: true

    grafana:
      enabled: true

    prometheus:
      enabled: true

    servicegraph:
      enabled: true

    tracing:
      enabled: true

    certmanager:
      enabled: true

