---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
spec:
  chartGitPath: podinfo
  releaseName: podinfo
  values:
    image:
      repository: quay.io/stefanprodan/podinfo
      tag: 1.2.0
