apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: demo
spec:
  peers:
  - mtls: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: demo
spec:
  host: "*.demo.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: permissive
  namespace: demo
spec:
  targets:
  - name: frontend
  peers:
  - mtls:
      mode: PERMISSIVE
