# Default values for backend demo.

# expose the store deployment inside the cluster
host: store

# load balance 80/20 between blue and green
blue:
  replicas: 2
  image: quay.io/stefanprodan/podinfo:1.0.0
  backend: https://httpbin.org/anything
  weight: 80

green:
  replicas: 2
  image: quay.io/stefanprodan/podinfo:1.0.0
  backend: https://httpbin.org/anything

externalServices:
  - httpbin.org
